### ISSUE TITLE
Invalid Mnemonic when running yarn test

### ISSUE THREAD

**Issue by jebscc** [XYOracleNetwork/sdk-xyo-client-js#787]
Got the compile issue resolved but now I am getting "Invalid Mnemonic" when running the test command. I quickly looked through a few files but haven't seen a place to insert a mnemonic phase. Is this step done for me or do I need to provide a test code with a mnemonic phase?

jebscc@DESKTOP-IAEVS68:/mnt/c/xyo/sdk-xyo-client-js$ yarn test
Determining test suites to run...
Mongo: Starting
Mongo: Started
Node: Starting
Error: Jest: Got error running globalSetup - /mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/test/src/globalSetup.ts, reason: invalid mnemonic
    at mnemonicToEntropy (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@ethersproject/hdnode/src.ts/index.ts:322:43)
    at Function.HDNode.fromMnemonic (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@ethersproject/hdnode/src.ts/index.ts:267:38)
    at getPrivateKeyFromMnemonic (/mnt/c/xyo/sdk-xyo-client-js/packages/protocol/packages/account/src/Account.ts:22:23)
    at Function.Account.fromMnemonic (/mnt/c/xyo/sdk-xyo-client-js/packages/protocol/packages/account/src/Account.ts:65:35)
    at setupNode (/mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/test/src/globalSetup.ts:41:39)
    at module.exports (/mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/test/src/globalSetup.ts:60:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/core/build/runGlobalHook.js:109:13
    at waitForPromiseWithCleanup (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/transform/build/ScriptTransformer.js:160:5)
    at ScriptTransformer.requireAndTranspileModule (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/transform/build/ScriptTransformer.js:805:16)
    at runGlobalHook (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/core/build/runGlobalHook.js:101:9)
    at runJest (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/core/build/runJest.js:327:5)
    at _run10000 (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/core/build/cli/index.js:344:7)
    at runCLI (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@jest/core/build/cli/index.js:199:3)
    at Object.run (/mnt/c/xyo/sdk-xyo-client-js/node_modules/jest-cli/build/run.js:124:37)

**Comment by jebscc** [comment]
This appears to be a manual input for the time being as the mnemonic phase has to be entered into files containing the following line:

const mnemonic = process.env.MNEMONIC || ''

After inserting the mnemonic phase into this line, I am now getting this message which is basically asking me for API KEY. This will most likely stop me as I haven't seen a way to generate this key. Time to read more code and see if it leads me in any direction to get the KEY.

Error: API_KEY ENV VAR required to create Archivist
    at assertEx (/mnt/c/xyo/sdk-xyo-client-js/node_modules/@xylabs/assert/src/index.ts:23:9)
    at /mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/dependencies/src/inversify.config.ts:34:26
    at Generator.next (<anonymous>)
    at /mnt/c/xyo/sdk-xyo-client-js/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/mnt/c/xyo/sdk-xyo-client-js/node_modules/tslib/tslib.js:163:16)
    at configureDependencies (/mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/dependencies/src/inversify.config.ts:30:66)
    at /mnt/c/xyo/sdk-xyo-client-js/packages/node/packages/express/packages/server/src/index.ts:45:30
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/c/xyo/sdk-xyo-client-js/node_modules/tslib/tslib.js:164:62)

**Comment by jebscc** [comment]
Wait... Now I remember but can't complete this at this time as "https://archivist.xyo.network/archive" is currently giving me 'Server Not Found' message. What I need to do is create my own archivist then use the API Key generated.

**Comment by JoelBCarter** [comment]
I updated the `example.env` file to [include a mnemonic](https://github.com/XYOracleNetwork/sdk-xyo-client-js/blob/540146ac92cd4f41eed636b19b40c7442540866b/.example.env#L26).  You can copy & rename that file to `.env` and the tests should pick up on it.  You can also follow that same format for inputting the mnemonic into the `.env` file but instead use the one generated from the [Node](https://node.xyo.network/settings?network=main) or [Explore](https://explore.xyo.network/settings?network=main) sites. So you can maintain the same identity locally as well as when running against the XYO sites.

**Comment by jebscc** [comment]
Thank you Joel. I'll pick this up again this afternoon and complete my tests. The mnemonic I previously used was generated by the Explore website.

**Comment by jebscc** [comment]
Nice!!! Now I am getting somewhere. Now just need to read up on Mongo as it appears its trying to connect to local Mongo service.

^Cjebscc@DESKTOP-IAEVS68:/mnt/c/xyo/sdk-xyo-client-js$ yarn xy test -c true
Test [@xyo-network/sdk-xyo-client-js]
Determining test suites to run...
Mongo: Starting
Mongo: Started
Node: Starting
MongoDBBoundWitnessStatsDiviner.RegisterWithChangeStream: Registering
MongoDBPayloadStatsDiviner.RegisterWithChangeStream: Registering
MongoDBSchemaStatsDiviner.RegisterWithChangeStream: Registering
MongoDBBoundWitnessStatsDiviner.RegisterWithChangeStream: Registered
MongoDBPayloadStatsDiviner.RegisterWithChangeStream: Registered
MongoDBSchemaStatsDiviner.RegisterWithChangeStream: Registered
{"date":"Thu Apr 06 2023 17:46:01 GMT-0400 (Eastern Daylight Time)","error":{"reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"}},"exception":true,"level":"error","message":"unhandledRejection: connect ECONNREFUSED 127.0.0.1:27017\nMongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (/mnt/c/xyo/sdk-xyo-client-js/node_modules/agenda/node_modules/mongodb/src/sdam/topology.ts:591:30)\n    at listOnTimeout (node:internal/timers:573:17)\n    at processTimers (node:internal/timers:514:7)","os":{"loadavg":[0.92,0.79,0.58],"uptime":83923.74},"process":{"argv":["/usr/local/bin/node","/mnt/c/xyo/sdk-xyo-client-js/node_modules/jest/bin/jest.js","."],"cwd":"/mnt/c/xyo/sdk-xyo-client-js","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":54087885,"external":56888458,"heapTotal":370692096,"heapUsed":359292544,"rss":475303936},"pid":5906,"uid":1000,"version":"v19.8.1"},"stack":"MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (/mnt/c/xyo/sdk-xyo-client-js/node_modules/agenda/node_modules/mongodb/src/sdam/topology.ts:591:30)\n    at listOnTimeout (node:internal/timers:573:17)\n    at processTimers (node:internal/timers:514:7)","timestamp":"2023-04-06T21:46:01.339Z","trace":[{"column":30,"file":"/mnt/c/xyo/sdk-xyo-client-js/node_modules/agenda/node_modules/mongodb/src/sdam/topology.ts","function":"Timeout._onTimeout","line":591,"method":"_onTimeout","native":false},{"column":17,"file":"node:internal/timers","function":"listOnTimeout","line":573,"method":null,"native":false},{"column":7,"file":"node:internal/timers","function":"processTimers","line":514,"method":null,"native":false}]}

**Comment by jebscc** [comment]
I see what needs to happen now and why I am getting this error. Time to build an archivist!!! Why didn't I think of this sooner!?
